---
# Address & route should run by script
- include: address.yml
  tags: [ 'role::mikrotik_ip:address']

- include: routes.yml
  tags: [ 'role::mikrotik_ip:routes']

- include: settings.yml
  tags: [ 'role::mikrotik_ip:settings' ]

- include: services.yml
  tags: [ 'role::mikrotik_ip:services' ]
